name: Publish Composer (Packagist) Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Update Packagist
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=syniol&apiToken='$PACKAGIST_TOKEN -d'{"repository":{"url":"https://github.com/syniol/xyo-sdk-php"}}' | exit 1



